### ISSUE TITLE
Доп. полезная монетизация

### ISSUE THREAD

**Issue by hackerspace-team** [theurs/tb1#1]
Сделать возможность получать доп. пользу от юзера при истечении лимита или перед стартом. Например подписаться на канал(ы), сделать проверку подписки чтобы отбивать платные функции ботов.

**Comment by theurs** [comment]
Добавил в конфиг настройки группы куда должен быть подписан юзер

# id группы на которую юзеры должны подписаться что бы юзать бота
# бот должен быть в группе и возможно иметь какие то права что бы проверять есть ли в ней юзер
# subscribe_channel_id = -xxx
# subscribe_channel_mes = 'Подпишитесь на наш канал http://t.me/blabla'
# subscribe_channel_cache = 3600*24 # сутки
