### ISSUE TITLE
Определение с какой моделью работаешь

### ISSUE THREAD

**Issue by antonysv** [theurs/tb1#3]
Можно как-то быстро определить, с какой моделью общаешься? И переключение моделей кнопками /config на что-то влияет, если указан бесплатный ключ в /openrouter и в /model указана какая-нибудь модель?

**Comment by theurs** [comment]
Команда /id покажет какая модель выбрана. Хотя ответить может и другая. Например если выбрана джемини но она не ответила из за цензуры вместо нее ответит ллама, и ответ от ламы будет помещен в память джемини как ее собственный ответ, и с большой вероятностью дальше джемини уже не будет выеживаться с цензурой (типа если я такую гадость только что сказала значит можно уже не парится и спокойно продолжать в том же духе).

Опенроутер можно выбрать через /config или включить его командой /openrouter. В /config он появляется если был настроен, если ему дали ключ.
Выбранная /model работает только в опенроутере. Опять же есть нюансы, если эта модель не отвечает на картинки(может она вообще не умеет) то на картинки ответит другая модель, из бесплатных.

**Comment by antonysv** [comment]
спасибо
